export type Gem =
  | "Chipped Topaz"
  | "Flawed Topaz"
  | "Topaz"
  | "Flawless Topaz"
  | "Perfect Topaz"
  | "Chipped Amethyst"
  | "Flawed Amethyst"
  | "Amethyst"
  | "Flawless Amethyst"
  | "Perfect Amethyst"
  | "Chipped Sapphire"
  | "Flawed Sapphire"
  | "Sapphire"
  | "Flawless Sapphire"
  | "Perfect Sapphire"
  | "Chipped Ruby"
  | "Flawed Ruby"
  | "Ruby"
  | "Flawless Ruby"
  | "Perfect Ruby"
  | "Chipped Emerald"
  | "Flawed Emerald"
  | "Emerald"
  | "Flawless Emerald"
  | "Perfect Emerald"
  | "Chipped Diamond"
  | "Flawed Diamond"
  | "Diamond"
  | "Flawless Diamond"
  | "Perfect Diamond";
